export const inputsData = [
  'Etre riche',
  'Aider les autres',
  'Faire une contribution',
  'Avoir une vie tranquille',
  'Etre créatif',
  'Organiser les choses',
  'Concevoir des choses',
  'Enseigner aux autres',
  'Profiter de la musique, de l\'art, du théâtre',
  'Faire des travaux pratiques',
  'Avoir une vie passionnante',
  'S\'engager dans un travail clairement défini',
  'Avoir une vie aventureuse',
  'Etre à l\'abri du danger',
  'Avoir une vie remplie de changement',
  'Etre responsable',
  'Etre en forme physique',
  'Gagner en sagesse',
  'Manger de la nourriture saine',
  'Vivre des états d\'humeur positives',
  'Se livrer à des activités sportives',
  'Construire et réparer des choses',
  'Respecter les traditions',
  'Rechercher le plaisir',
  'Etre auto-discipliner',
  'Créer des belles choses',
  'Respecter les parents et les aînés',
  'Etre admiré par les gens',
  'Mener une vie sans stress',
  'Etre en compétition avec des autres',
  'Résoudre des disputes',
  'Accepter les autres comme ils sont',
  'Travailler avec mes mains',
  'Prendre soin des faibles',
  'Rechercher des choses',
  'Etre connecter avec la nature',
  'Agir avec courage',
  'Remplir mes obligations',
  'Se soucier des autres',
  'Avoir de l\'influence sur les gens',
  'Etre loyal',
  'Etre honnête',
  'Avoir de vrais amis',
  'Ne pas être redevable aux gens',
  'Avoir des relations amoureuses',
  'Etre ambitieux',
  'Etre compétent',
  'Etre curieux',
  'Garder ses proches en sécurité',
  'Etre auto-suffisant',
  'Profiter de la nourriture et des boissons',
  'Se sentir bien dans ma peau',
  'Comprendre les choses',
  'S\'efforcer d\'être une meilleure personne',
];
export const inputsData2 = [
  'Etre riche',
  'Faire une contribution',
  'Comprendre les choses',
  'S\'efforcer d\'être une meilleure personne',
  'Profiter de la nourriture et des boissons',
  'Se sentir bien dans ma peau',
];

export const actions = {
  SET_STEPS: 'setStep',
  SET_RESULTS: 'setResults',
  SET_PROGRESS: 'setProgress',
  ADD_POINT: 'addPoint'
};
